### PR TITLE
Simple export

### PR DESCRIPTION
**Pull request by rgbkrk**
I'm hoping to use a common code base for the Jupyter messaging protocol, in my case for some alternative front end bits.

This sets up Message to be exported from jp.js (since that's all that comes out). I'm open to having more exposed but this is all I needed at the moment.

### CODE REVIEW

**Comment by n-riesco** [comment]
That's great! Would it help if I move the `jp` module into its own `npm` package?

Here are my thoughts about the pull request. 
* I don't understand the need to use `lib/index.js`. Wouldn't it be enough to require `./lib/jp.js` directly from `index.js`?
* I don't understand the need to define `jupyter` globally. I think the decision should be left to the importer:
    * `var jupyter = require("ijavascript");` to import locally
    * `jupyter = require("ijavascript");` to import globally

**Comment by rgbkrk** [comment]
What I ended up doing last night was

```javascript
var Message = require('ijavascript/lib/jp.js');
```

I'm *extremely* new to packaging node application, so I'm willing to change this to any way you like it.

**Comment by rgbkrk** [comment]
Updated it to only export jp.js.

**Comment by n-riesco** [comment]
After some more thought, this is where I stand:
* IJavascript is mainly a Jupyter kernel and an alternative to the node.js REPL
* I'm very happy with the idea that other people use `jp` in their code
* IJavascript also defines module `sm` to provide access to node.js sessions.
* I'm considering distributing `sm` as its own `npm` package
* Since the users of IJavascript, `sm` and `jp` may have different interests, it makes more sense that IJavascript, `sm` and `jp` are distributed independently

For those reasons, I've decided to move `jp` into its own [`npm` package](https://www.npmjs.com/package/jmp). I've renamed the module as `jmp` (Jupyter Messaging Protocol), because the `jp` is already taken. I've also changed the way to import class `Message` (so that I can export other symbols in the future).

To use the new package, you can replace:
```javascript
var Message = require('ijavascript/lib/jp.js');
```
with:
```javascript
var Message = require('jmp').Message;
```

Please, let me know if this change wouldn't work for you.

**Comment by rgbkrk** [comment]
Totally works for me!

I'm likely duplicating code that could be propagating converted messages, perhaps we can build up some other tooling that submits Message events?

```JavaScript
/**
 * @class Snupyter
 * @classdesc Snoops on messages from a Jupyter kernel
 * @param {Object} connectionJSON Connection information provided by Jupyter
 */
function Snupyter(connectionJSON) {
  	/**
     * Connection information provided by Jupyter
     * @member {Object}
     */
    this.connectionJSON = connectionJSON;
    
    /** IOPub socket
     * @member {module:zmq~Socket}
     */
     this.iopubSocket = zmq.socket("sub");
     this.iopubURL = formConnectionString(this.connectionJSON, "iopub");

     console.log('Connecting to ' + this.iopubURL);

     this.iopubSocket.connect(this.iopubURL);
     this.iopubSocket.subscribe('');
     
     this.iopubSocket.on("message", onIOPubMessage.bind(this));
     
     function onIOPubMessage() {
       var msg = new Message(
         arguments,
         this.connectionJSON.signature_scheme.slice("hmac-".length),
         this.connectionJSON.key
       );
       console.dir(msg);
     }
    
}

var snupyter = new Snupyter(config);
```

I'm doing this to create an Electron app that can display outputs from Jupyter kernels, starting with an HTML side car to a console:

screenshot 2015-04-30 08 37 07

**Comment by n-riesco** [comment]
> I'm likely duplicating code that could be propagating converted messages,

I don't understand

> perhaps we can build up some other tooling that submits Message events?

sorry I don't understand this either (:() Could you give me an example?

I'm going offline now. It's likely I won't be able to come back to you until tomorrow.

**Comment by rgbkrk** [comment]
Hey, that's ok. In particular, I'm thinking we could use a generic message handler to pass a message on to a callback or a stream:

```
     function onMessage() {
       var msg = new Message(
         arguments,
         this.connectionJSON.signature_scheme.slice("hmac-".length),
         this.connectionJSON.key
       );
       // pass msg on somehow
     }
```

**Comment by n-riesco** [comment]
[This](https://github.com/n-riesco/jmp/commit/61ef852a7574dde013946041cb31611cb5cb6913) is what I came up over my tube journey:
* I've defined class `Socket` that inherits from ZMQ's Socket (and thus, it can be used where a ZMQ socket is used). It wraps all the listeners of "message" events so that they receive an instance of `Message`.
* Here's your updated code:
```JavaScript
/**
 * @class Snupyter
 * @classdesc Snoops on messages from a Jupyter kernel
 * @param {Object} connectionJSON Connection information provided by Jupyter
 */
function Snupyter(connectionJSON) {
  	/**
     * Connection information provided by Jupyter
     * @member {Object}
     */
    this.connectionJSON = connectionJSON;
    
    /** IOPub socket
     * @member {module:jmp~Socket}
     */
     this.iopubSocket = new jmp.Socket(
          "sub",
           this.connectionJSON.signature_scheme.slice("hmac-".length),
           this.connectionJSON.key
     );
     this.iopubURL = formConnectionString(this.connectionJSON, "iopub");

     console.log('Connecting to ' + this.iopubURL);

     this.iopubSocket.connect(this.iopubURL);
     this.iopubSocket.subscribe('');
     
     this.iopubSocket.on("message", onIOPubMessage.bind(this));
     
     function onIOPubMessage(msg) {
       console.dir(msg);
     }
    
}

var snupyter = new Snupyter(config);
```

**Comment by rgbkrk** [comment]
Beautiful @n-riesco! That's just what I was hoping for. Thank you.

**Comment by n-riesco** [comment]
:) Thanks.

I've only tested that message listeners can be added, get the messages and can be removed. At some point in the *nearish* future, I will add some proper tests.

**Pull request closed without merging**
