### PR TITLE
Use docstrap for documentation layout

### PR DESCRIPTION
**Pull request by benjaminabel**
Hi Nico, I worked on the documentation layout, you can see the result here: <http://benjaminabel.github.io/ijavascript/>

It uses docstrap as a dependencie, which include bootstrap, so I worked on a ipython template to remove duplicate css. 

Are you Ok, or would you like that I work on docstrap templates including them in the repo?

### CODE REVIEW

**Comment by n-riesco** [comment]
I can't see, in the issue tracker, the last few messages we've exchanged. I will post here where I am at the moment:
* I've noticed that the IPython notebook uses `pandoc`. This means we can use `pandoc` to convert `.md` files into HTML.
* Since I'd like to separate the `jsdoc` documentation from the user documentation, I'm thinking of generating the documentation from:

  README.md
  CONTRIBUTING.md
  doc/images
  doc/tutorials
  doc/jsdoc
  doc/jsdoc/tutorials

**Comment by benjaminabel** [comment]
Hi Nico, I'm working  on a way to do this using nbconvert and marked(node
dependencie).
You can view work in progress on my branch named user-documentation. I'll
push some commits tonight with some explanations on the way I do this.
Le 29 avr. 2015 8:45 PM, "Nicolas Riesco" <notifications@github.com> a
écrit :

**Comment by n-riesco** [comment]
In case it helps, here's how you convert from `.md` to HTML using `pandoc`:
```
pandoc --standalone --from=markdown_github-hard_line_breaks --to=html --output=file.html file.md
```
or if there is need for embedding the images:
```
pandoc --seld-contained --from=markdown_github-hard_line_breaks --to=html --output=file.html file.md
```

PS: I'm working on a logo for IJavascript.

**Comment by benjaminabel** [comment]
Here's a sample with a first push to gh-pages <http://benjaminabel.github.io/ijavascript/>, the branch is here: <https://github.com/benjaminabel/ijavascript/tree/user-documentation>

**Comment by n-riesco** [comment]
looks neat

**Comment by benjaminabel** [comment]
I've updated navbar and files conversion à la main. I think we could use a json or yml file to store these information like in the build tool mkdocs, see an example here <https://github.com/tomchristie/django-rest-framework/blob/master/mkdocs.yml>

**Pull request closed without merging**
