### PR TITLE
Merge master with await

### PR DESCRIPTION
**Pull request by ezyang**
Await branch no longer builds on newer npm because zeromq is too old; master has the fix for this so merge it in.

### CODE REVIEW

**Comment by n-riesco** [comment]
See https://github.com/n-riesco/ijavascript/issues/173#issuecomment-974690391

Closing this PR as top level await is already supported by Node.js v16.6+ out of the box.

**Comment by Herts** [comment]
@n-riesco Will this feature be merged in the future?

**Comment by n-riesco** [comment]
@Herts `ijavascript`'s `master` was merged into `ijavascript-await` [here](https://github.com/n-riesco/ijavascript/commit/e854b17bad29785cfc38b7eda23aa5a6fe1b4915).

Note that `ijavascript-await` uses a parser (`acorn`) to implement this feature.

I don't have plans to stop supporting `ijavascript` as a kernel to the `node.js` REPL. Unfortunately, I haven't figured out a solution to https://github.com/nodejs/node/issues/40898 that only makes use of the `node.js` REPL.

**Comment by Herts** [comment]
@n-riesco Thank you so much for your reply. I've already put that branch in use. It's a great project and I appreciate it.

**Comment by n-riesco** [comment]
@Herts It's also distributed through npm: https://www.npmjs.com/package/ijavascript-await

**Pull request closed without merging**
