### PR TITLE
User documentation

### PR DESCRIPTION
**Pull request by benjaminabel**
Hi Nico, I think that's all.
I added a `doc:style` npm script to include ipython inline css in a file that can be shared across doc and api doc. And fixed links and README.

### CODE REVIEW

**Comment by n-riesco** [comment]
I've been reviewing your commits and I've noticed some files that I think need copyright notices:
* Add doc/images/Unofficial_JavaScript_logo.LICENSE
* Add LICENSE file to folder doc/templates/jsdoc_templates
* Is it possible to add a copyright notices to:?
  * doc/jsdoc_config.json
  * doc/templates/ipython.tpl
  * doc/templates/_navbar.tpl
  * doc/templates/ipython_style.tpl
  * doc/templates/empty_md.ipynb

Some of the files above have been taken or adapted from other projects. The LICENSE from those projects needs to be included.

**Comment by benjaminabel** [comment]
Hi Nico,

Thanks for your review.

> Add doc/images/Unofficial_JavaScript_logo.LICENSE

Maybe we could use the ijavascript logo here. Also, are you sure you want
to stay on nbformat 3 for tutorials notebooks as these are for dev use.

> Add LICENSE file to folder doc/templates/jsdoc_templates

You're right

> Is it possible to add a copyright notices to:?
> doc/jsdoc_config.json
> doc/templates/ipython.tpl
> doc/templates/_navbar.tpl
> doc/templates/ipython_style.tpl
> doc/templates/empty_md.ipynb

I think the only file which might need a copyright here is Ipython.tpl and
I'm not really sure. Do you want to ask to the ipython team?

> Some of the files above have been taken or adapted from other projects.
The LICENSE from those projects needs to be included.

**Comment by n-riesco** [comment]
Could post here a link to were the logo is coming from? I will try to dig its license for you.

**Comment by benjaminabel** [comment]
I created the fake logo, we can replace it later when there will be a real
one.

**Comment by rgbkrk** [comment]
> Do you want to ask to the ipython team?

From https://github.com/ipython/ipython/blob/master/COPYING.rst#our-copyright-policy, include this in a comment within the file:

> Copyright (c) IPython Development Team.
> Distributed under the terms of the Modified BSD License.

Spoken as member of IPython and Jupyter.

**Comment by benjaminabel** [comment]
OK thanks for your reply, I'll add the notice.

**Comment by n-riesco** [comment]
Thanks Kyle

**Pull request merged**
