### PR TITLE
Updated Readme to remove `sudo npm`

### PR DESCRIPTION
**Pull request by brendannee**

### CODE REVIEW

**Comment by n-riesco** [comment]
In Ubuntu (unless configured otherwise) `npm install -g ijavascript` requires admin rights.

Or am I missing something?

BTW, I've been preparing an update of the documentation. You can find it in the [dev branch](https://github.com/n-riesco/ijavascript/tree/dev).

**Comment by rgbkrk** [comment]
For anyone using nvm or other local node environments we don't use sudo whatsoever. Same thing applies to when used in a Docker container. A lot of newer node users will end up using nvm, read instructions like these that recommend sudo, then wonder why things are broken/not working for them.

I tend not to include sudo in instructions because of this. For users that need it, they can choose to pretend it.

**Comment by n-riesco** [comment]
@rgbkrk Rather than breaking the instructions for Ubuntu users, we should add a section for `nvm` and `docker` users (though, I don't follow why `sudo` wouldn't work for `nvm` users).

**Comment by rgbkrk** [comment]
> I don't follow why sudo wouldn't work for nvm users

`sudo` will be the system environment rather than their nvm environment (default or some configured install).

**Comment by n-riesco** [comment]
Closed in favour of https://github.com/n-riesco/ijavascript/commit/e4801047ae0bb53ca72a8f421271d8427cd09990

**Pull request closed without merging**
