### PR TITLE
Addition of conda section to installation documentation

### PR DESCRIPTION
**Pull request by krinsman**
as mentioned here: https://github.com/n-riesco/ijavascript/issues/153#issuecomment-397087223

### CODE REVIEW

**Comment by n-riesco** [comment]
Looks good!

Could you also add your name to the list of [AUTHORS](https://github.com/n-riesco/ijavascript/blob/master/AUTHORS)? I ask contributors to add their names, to confirm their consent to distributing their contributions under the terms in [LICENSE](https://github.com/n-riesco/ijavascript/blob/master/LICENSE).

**Comment by krinsman** [comment]
@n-riesco How does one do that?

I have no problem with doing that, I just don't know how to do that.

**Comment by n-riesco** [comment]
@krinsman What I meant is to add a commit to update the file [AUTHORS](https://github.com/n-riesco/ijavascript/blob/master/AUTHORS). `AUTHORS` keeps a list of contributor's names and contact emails.

Do you know how to update this PR to change the file `AUTHORS`?

**Comment by krinsman** [comment]
@n-riesco Is the list alphabetized by first name? I wanted to keep the list sorted but wasn't 100% certain what the sorting criterion is.

Sorry for not having seen that file earlier.

**Comment by n-riesco** [comment]
@krinsman Thanks!

> Is the list alphabetized by first name? I wanted to keep the list sorted but wasn't 100% certain what the sorting criterion is.

yes, that's the order (if we define ["first name"](https://en.wikipedia.org/wiki/Personal_name#Name_order) as the name we write first :smile: ).

**Pull request merged**
